// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../app/categorias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categorias">> = Specific
  const handler = {} as typeof import("../../../app/categorias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/convocatorias/Asenso/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/convocatorias/Asenso">> = Specific
  const handler = {} as typeof import("../../../app/convocatorias/Asenso/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/convocatorias/cambio_grupo_ocupacional/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/convocatorias/cambio_grupo_ocupacional">> = Specific
  const handler = {} as typeof import("../../../app/convocatorias/cambio_grupo_ocupacional/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/convocatorias/cas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/convocatorias/cas">> = Specific
  const handler = {} as typeof import("../../../app/convocatorias/cas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/convocatorias/dl-276/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/convocatorias/dl-276">> = Specific
  const handler = {} as typeof import("../../../app/convocatorias/dl-276/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/convocatorias/dl-728/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/convocatorias/dl-728">> = Specific
  const handler = {} as typeof import("../../../app/convocatorias/dl-728/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/convocatorias/locacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/convocatorias/locacion">> = Specific
  const handler = {} as typeof import("../../../app/convocatorias/locacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/convocatorias/nombramiento-administrativo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/convocatorias/nombramiento-administrativo">> = Specific
  const handler = {} as typeof import("../../../app/convocatorias/nombramiento-administrativo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/convocatorias/nombramiento-asistencial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/convocatorias/nombramiento-asistencial">> = Specific
  const handler = {} as typeof import("../../../app/convocatorias/nombramiento-asistencial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/convocatorias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/convocatorias">> = Specific
  const handler = {} as typeof import("../../../app/convocatorias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/convocatorias/practicas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/convocatorias/practicas">> = Specific
  const handler = {} as typeof import("../../../app/convocatorias/practicas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/convocatorias/reasignacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/convocatorias/reasignacion">> = Specific
  const handler = {} as typeof import("../../../app/convocatorias/reasignacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/rrhh/contacto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rrhh/contacto">> = Specific
  const handler = {} as typeof import("../../../app/rrhh/contacto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/rrhh/desarrollo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rrhh/desarrollo">> = Specific
  const handler = {} as typeof import("../../../app/rrhh/desarrollo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/rrhh/documentos-normativos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rrhh/documentos-normativos">> = Specific
  const handler = {} as typeof import("../../../app/rrhh/documentos-normativos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/rrhh/gestion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rrhh/gestion">> = Specific
  const handler = {} as typeof import("../../../app/rrhh/gestion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/rrhh/oportunidad-laboral/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rrhh/oportunidad-laboral">> = Specific
  const handler = {} as typeof import("../../../app/rrhh/oportunidad-laboral/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/rrhh/serums/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rrhh/serums">> = Specific
  const handler = {} as typeof import("../../../app/rrhh/serums/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
